name = "project_roadwork/talk_eligibility"
version = "1.0.0-beta.2"
description = "Checks which players can chat with one another based on ROBLOX chat permissions."
authors = ["Illinois_Roadbuff [Rogue Jr]"]
repository = "https://codeberg.org/project-roadwork/talk-eligibility.git"
license = "Apache-2.0 WITH LLVM-exception"
includes = ["pesde.toml","README.md","LICENSE","NOTICE","src/**/*.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
