[package]
name = "illinois-roadbuff/talk-eligibility"
version = "1.0.0-alpha.3"
description = "Checks which players can chat with one another based on ROBLOX chat permissions."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "Apache-2.0 WITH LLVM-exception"
includes = ["LICENSE","NOTICE","src/**/*.luau"]
repository = "https://codeberg.org/project-roadwork/talk-eligibility.git"
authors = ["Illinois_Roadbuff [Rogue Jr] <illinois_roadbuff@proton.me>"]

[dependencies]
