--[[

	SPDX-FileCopyrightText:   Copyright (c) 2026 breadboardengineer1234
	Derived from: https://github.com/breadboardengineer1234/QuickNet.git

	SPDX-License-Identifier:   MIT

]]

local module = {
	[1] = "whatever",
	[2] = "number",
	[3] = "number",
	[4] = "number",
	[5] = "number",
	[6] = "number",
	[7] = "number",
	[8] = "number",
	[9] = "number",
	[10] = "number",
	[11] = "number",

	[12] = "CFrame",
	[13] = "CFrame",
	[14] = "CFrame",
	[15] = "CFrame",
	[16] = "CFrame",
	[17] = "CFrame",
	[18] = "CFrame",

	[19] = "Vector3",
	[20] = "Vector3",
	[21] = "Vector3",
	[22] = "Vector3",
	[23] = "Vector3",

	[24] = "Vector2",
	[25] = "Vector2",
	[26] = "Vector2",
	[27] = "Vector2",
	[28] = "Vector2",

	[29] = "string",
	[30] = "string",
	[31] = "Color3",
	[32] = "BrickColor",
	[33] = "boolean",
	[34] = "nil",
	[35] = "buffer",
	[36] = "EnumItem",
	[37] = "Instance",
	[38] = "Player",
	[39] = "DateTime",
	[40] = "DateTime",
	[41] = "TweenInfo",
	[42] = "ColorSequence",
	[43] = "NumberSequence",
	[44] = "NumberRange",
	[45] = "UDim",
	[46] = "UDim2",
	[47] = "Region3",
	[48] = "PhysicalProperties",
	[49] = "Rect",
}

return module
