--[[

	SPDX-FileCopyrightText:   Copyright (c) 2026 breadboardengineer1234
	Derived from: https://github.com/breadboardengineer1234/QuickNet.git

	SPDX-License-Identifier:   MIT

]]

local enums = {
	Start = 1,
	NumberU4 = 2,
	["NumberU8"] = 3,
	["NumberU16"] = 4,
	["NumberU32"] = 5,
	["NumberI8"] = 6,
	["NumberI16"] = 7,
	["NumberI32"] = 8,
	["NumberF16"] = 9,
	["NumberF32"] = 10,
	["NumberF64"] = 11,

	["CFrameFX8"] = 12,
	CFrameI16FX16 = 13,
	["CFrameFX16"] = 14,
	["CFrameF16"] = 15,
	CFrameF32Aligned = 16,
	["CFrameF32FX16"] = 17,
	["CFrameF32"] = 18,

	["Vector3FX8"] = 19,
	Vector3I16 = 20,
	["Vector3FX16"] = 21,
	["Vector3F16"] = 22,
	["Vector3F32"] = 23,

	["Vector2FX8"] = 24,
	Vector2I16 = 25,
	["Vector2FX16"] = 26,
	["Vector2F16"] = 27,
	["Vector2F32"] = 28,

	["String"] = 29,
	StringLong = 30,
	["Color3"] = 31,
	BrickColor = 32,
	["Boolean"] = 33,
	["Nil"] = 34,
	Buffer = 35,
	EnumItem = 36,
	Instance = 37,
	Player = 38,
	DateTime32 = 39,
	DateTime64 = 40,
	TweenInfo = 41,
	ColorSequence = 42,
	NumberSequence = 43,
	NumberRange = 44,
	UDim = 45,
	UDim2 = 46,
	Region3 = 47,
	PhysicalProperties = 48,
	Rect = 49,

	["Any"] = 50,
	Optional = 51,
	Union = 52,
	Literal = 53,
	["ArrayStatic"] = 54,
	["Array"] = 55,
	["ArrayDynamic"] = 56,
	["DictStatic"] = 57,
	["Dict"] = 58,
	["DictDynamic"] = 59,

	FastNumberU4Array = 60,
	FastNumberU8Array = 61,
	FastNumberI32Array = 62,
	FastNumberF32Array = 63,
	FastBoolArray = 64,
	FastStringArray = 65,
	FastNumberU8DictStatic = 66,
	FastNumberI32DictStatic = 67,
	FastNumberF32DictStatic = 68,
	FastBoolDictStatic = 69,
	FastStringDictStatic = 70,
	FastNumberU8Dict = 71,
	FastNumberI32Dict = 72,
	FastNumberF32Dict = 73,
	FastBoolDict = 74,
	FastStringDict = 75,
}

return enums
